package com.hrznstudio.escapade.biome.crimson;

import net.minecraft.block.Blocks;
import net.minecraft.entity.EntityClassification;
import net.minecraft.entity.EntityType;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.DefaultBiomeFeatures;
import net.minecraft.world.gen.GenerationStage.Decoration;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.OreFeatureConfig;
import net.minecraft.world.gen.feature.OreFeatureConfig.FillerBlockType;
import net.minecraft.world.gen.placement.CountRangeConfig;
import net.minecraft.world.gen.placement.Placement;

/**
 * // Crimson Weald //
 * The Crimson Weald is a heavily vegetized forest area filled with abandoned Illager Structures.
 * Most if not all blocks are infused by the heavy presence Redstone in the Biome.
 * This biome has a highly greater chance to spawn Redstone ore and also has breakable Redstone Crystals underground.
 *
 * "Structure-wise" this biome should be a larger-scale heavily forested area with Illager structures such as Guard Posts, Watchtowers, Illager Villages(?), and Redstone Mines.
 * Precipitation should be renderer as much "Red-er" rain, due to the rain being infused with the raw Redstone Fog Clouds in the biome, generated by the active Redstone mines.
 *
 */
public class CrimsonWealdBiome extends Biome {

    public CrimsonWealdBiome() {
        super(new Biome.Builder().waterColor(32767).waterFogColor(32767).precipitation(RainType.RAIN).downfall(0.5f).temperature(0.175f));

        // Add default features
        DefaultBiomeFeatures.addFossils(this);
        DefaultBiomeFeatures.addLakes(this);

        // Add extra Lapis Lazuli ore generation.
        this.addFeature(Decoration.UNDERGROUND_ORES, Feature.ORE.withConfiguration(new OreFeatureConfig(FillerBlockType.NATURAL_STONE, Blocks.REDSTONE_ORE.getDefaultState(), 9)).withPlacement(Placement.COUNT_RANGE.configure(new CountRangeConfig(20, 32, 32, 80))));

        // Clear the default Monster List and Add Illager Spawns
        this.getSpawns(EntityClassification.MONSTER).clear();
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.EVOKER, 5, 1, 3));
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.ILLUSIONER, 10, 1, 3));
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.PILLAGER, 20, 1, 3));
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.RAVAGER, 5, 1, 2));
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.VINDICATOR, 15, 1, 3));
        this.addSpawn(EntityClassification.MONSTER, new SpawnListEntry(EntityType.WITCH, 10, 1, 3));

        // TODO: Add Custom Miner and Summoner Illagers
    }



}
